# Generated by Django 2.2.6 on 2019-10-09 16:18

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('published_date', models.DateField()),
                ('page_count', models.IntegerField()),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ImageLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_thumbnail', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('thumbnail', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('small', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('medium', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('large', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('extraLarge', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='IndustryIdentifiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('identifier', models.TextField(unique=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka_app.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='image_links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Biblioteka_app.ImageLinks'),
        ),
    ]
